/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["de", "en", "ru", "cs"]);
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "editor",
  "author",
  "poc-photographer",
]);
export const enum_pages_type = pgEnum("enum_pages_type", [
  "pillar",
  "info-hub",
  "landing",
]);
export const enum_pages_ensana_c_t_a_position = pgEnum(
  "enum_pages_ensana_c_t_a_position",
  ["sidebar", "inline", "bottom"],
);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_version_type = pgEnum("enum__pages_v_version_type", [
  "pillar",
  "info-hub",
  "landing",
]);
export const enum__pages_v_version_ensana_c_t_a_position = pgEnum(
  "enum__pages_v_version_ensana_c_t_a_position",
  ["sidebar", "inline", "bottom"],
);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum__pages_v_published_locale = pgEnum(
  "enum__pages_v_published_locale",
  ["de", "en", "ru", "cs"],
);
export const enum_articles_type = pgEnum("enum_articles_type", [
  "cluster",
  "seasonal",
  "expert",
  "listicle",
]);
export const enum_articles_ensana_c_t_a_position = pgEnum(
  "enum_articles_ensana_c_t_a_position",
  ["sidebar", "inline", "bottom"],
);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "review",
  "published",
]);
export const enum__articles_v_version_type = pgEnum(
  "enum__articles_v_version_type",
  ["cluster", "seasonal", "expert", "listicle"],
);
export const enum__articles_v_version_ensana_c_t_a_position = pgEnum(
  "enum__articles_v_version_ensana_c_t_a_position",
  ["sidebar", "inline", "bottom"],
);
export const enum__articles_v_version_status = pgEnum(
  "enum__articles_v_version_status",
  ["draft", "review", "published"],
);
export const enum__articles_v_published_locale = pgEnum(
  "enum__articles_v_published_locale",
  ["de", "en", "ru", "cs"],
);
export const enum_people_stories_original_language = pgEnum(
  "enum_people_stories_original_language",
  ["de", "en", "ru", "cs", "other"],
);
export const enum_people_stories_archetype = pgEnum(
  "enum_people_stories_archetype",
  [
    "loyal",
    "first-visit",
    "healing",
    "love",
    "generation",
    "cultural",
    "local",
    "faraway",
  ],
);
export const enum_people_stories_status = pgEnum("enum_people_stories_status", [
  "draft",
  "published",
]);
export const enum__people_stories_v_version_original_language = pgEnum(
  "enum__people_stories_v_version_original_language",
  ["de", "en", "ru", "cs", "other"],
);
export const enum__people_stories_v_version_archetype = pgEnum(
  "enum__people_stories_v_version_archetype",
  [
    "loyal",
    "first-visit",
    "healing",
    "love",
    "generation",
    "cultural",
    "local",
    "faraway",
  ],
);
export const enum__people_stories_v_version_status = pgEnum(
  "enum__people_stories_v_version_status",
  ["draft", "published"],
);
export const enum__people_stories_v_published_locale = pgEnum(
  "enum__people_stories_v_published_locale",
  ["de", "en", "ru", "cs"],
);
export const enum_events_category = pgEnum("enum_events_category", [
  "culture",
  "sport",
  "wellness",
  "festival",
  "other",
]);
export const enum_events_status = pgEnum("enum_events_status", [
  "upcoming",
  "ongoing",
  "past",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    role: enum_users_role("role").notNull().default("editor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const pages_table_of_contents = pgTable(
  "pages_table_of_contents",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    anchor: varchar("anchor"),
  },
  (columns) => [
    index("pages_table_of_contents_order_idx").on(columns._order),
    index("pages_table_of_contents_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_table_of_contents_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_table_of_contents_locales = pgTable(
  "pages_table_of_contents_locales",
  {
    label: varchar("label"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_table_of_contents_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_table_of_contents.id],
      name: "pages_table_of_contents_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_faq = pgTable(
  "pages_faq",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("pages_faq_order_idx").on(columns._order),
    index("pages_faq_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_faq_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_faq_locales = pgTable(
  "pages_faq_locales",
  {
    question: varchar("question"),
    answer: varchar("answer"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_faq_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_faq.id],
      name: "pages_faq_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_target_keywords = pgTable(
  "pages_target_keywords",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    keyword: varchar("keyword"),
  },
  (columns) => [
    index("pages_target_keywords_order_idx").on(columns._order),
    index("pages_target_keywords_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_target_keywords_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    type: enum_pages_type("type"),
    hero_backgroundImage: integer("hero_background_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    hero_ctaUrl: varchar("hero_cta_url"),
    ensanaCTA_enabled: boolean("ensana_c_t_a_enabled").default(false),
    ensanaCTA_url: varchar("ensana_c_t_a_url"),
    ensanaCTA_position: enum_pages_ensana_c_t_a_position(
      "ensana_c_t_a_position",
    ).default("sidebar"),
    status: enum_pages_status("status").default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    index("pages_hero_hero_background_image_idx").on(
      columns.hero_backgroundImage,
    ),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const pages_locales = pgTable(
  "pages_locales",
  {
    title: varchar("title"),
    slug: varchar("slug"),
    hero_headline: varchar("hero_headline"),
    hero_subheadline: varchar("hero_subheadline"),
    hero_ctaText: varchar("hero_cta_text"),
    content: jsonb("content"),
    ensanaCTA_headline: varchar("ensana_c_t_a_headline"),
    ensanaCTA_text: varchar("ensana_c_t_a_text"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug, columns._locale),
    index("pages_meta_meta_image_idx").on(columns.meta_image, columns._locale),
    uniqueIndex("pages_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_rels = pgTable(
  "pages_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    articlesID: integer("articles_id"),
  },
  (columns) => [
    index("pages_rels_order_idx").on(columns.order),
    index("pages_rels_parent_idx").on(columns.parent),
    index("pages_rels_path_idx").on(columns.path),
    index("pages_rels_articles_id_idx").on(columns.articlesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [pages.id],
      name: "pages_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "pages_rels_articles_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_table_of_contents = pgTable(
  "_pages_v_version_table_of_contents",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    anchor: varchar("anchor"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_table_of_contents_order_idx").on(columns._order),
    index("_pages_v_version_table_of_contents_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_version_table_of_contents_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_table_of_contents_locales = pgTable(
  "_pages_v_version_table_of_contents_locales",
  {
    label: varchar("label"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "_pages_v_version_table_of_contents_locales_locale_parent_id_",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v_version_table_of_contents.id],
      name: "_pages_v_version_table_of_contents_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_faq = pgTable(
  "_pages_v_version_faq",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_faq_order_idx").on(columns._order),
    index("_pages_v_version_faq_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_version_faq_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_faq_locales = pgTable(
  "_pages_v_version_faq_locales",
  {
    question: varchar("question"),
    answer: varchar("answer"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_pages_v_version_faq_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v_version_faq.id],
      name: "_pages_v_version_faq_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_target_keywords = pgTable(
  "_pages_v_version_target_keywords",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    keyword: varchar("keyword"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_target_keywords_order_idx").on(columns._order),
    index("_pages_v_version_target_keywords_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_version_target_keywords_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_type: enum__pages_v_version_type("version_type"),
    version_hero_backgroundImage: integer(
      "version_hero_background_image_id",
    ).references(() => media.id, {
      onDelete: "set null",
    }),
    version_hero_ctaUrl: varchar("version_hero_cta_url"),
    version_ensanaCTA_enabled: boolean("version_ensana_c_t_a_enabled").default(
      false,
    ),
    version_ensanaCTA_url: varchar("version_ensana_c_t_a_url"),
    version_ensanaCTA_position: enum__pages_v_version_ensana_c_t_a_position(
      "version_ensana_c_t_a_position",
    ).default("sidebar"),
    version_status:
      enum__pages_v_version_status("version_status").default("draft"),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__pages_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_hero_version_hero_background_image_idx").on(
      columns.version_hero_backgroundImage,
    ),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_snapshot_idx").on(columns.snapshot),
    index("_pages_v_published_locale_idx").on(columns.publishedLocale),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const _pages_v_locales = pgTable(
  "_pages_v_locales",
  {
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_hero_headline: varchar("version_hero_headline"),
    version_hero_subheadline: varchar("version_hero_subheadline"),
    version_hero_ctaText: varchar("version_hero_cta_text"),
    version_content: jsonb("version_content"),
    version_ensanaCTA_headline: varchar("version_ensana_c_t_a_headline"),
    version_ensanaCTA_text: varchar("version_ensana_c_t_a_text"),
    version_meta_title: varchar("version_meta_title"),
    version_meta_description: varchar("version_meta_description"),
    version_meta_image: integer("version_meta_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("_pages_v_version_version_slug_idx").on(
      columns.version_slug,
      columns._locale,
    ),
    index("_pages_v_version_meta_version_meta_image_idx").on(
      columns.version_meta_image,
      columns._locale,
    ),
    uniqueIndex("_pages_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_rels = pgTable(
  "_pages_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    articlesID: integer("articles_id"),
  },
  (columns) => [
    index("_pages_v_rels_order_idx").on(columns.order),
    index("_pages_v_rels_parent_idx").on(columns.parent),
    index("_pages_v_rels_path_idx").on(columns.path),
    index("_pages_v_rels_articles_id_idx").on(columns.articlesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "_pages_v_rels_articles_fk",
    }).onDelete("cascade"),
  ],
);

export const articles_tags = pgTable(
  "articles_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag"),
  },
  (columns) => [
    index("articles_tags_order_idx").on(columns._order),
    index("articles_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    type: enum_articles_type("type"),
    parentPillar: integer("parent_pillar_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    category: integer("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    author: integer("author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    featuredImage: integer("featured_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    ensanaCTA_enabled: boolean("ensana_c_t_a_enabled").default(false),
    ensanaCTA_url: varchar("ensana_c_t_a_url"),
    ensanaCTA_position: enum_articles_ensana_c_t_a_position(
      "ensana_c_t_a_position",
    ).default("sidebar"),
    status: enum_articles_status("status").default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_articles_status("_status").default("draft"),
  },
  (columns) => [
    index("articles_parent_pillar_idx").on(columns.parentPillar),
    index("articles_category_idx").on(columns.category),
    index("articles_author_idx").on(columns.author),
    index("articles_featured_image_idx").on(columns.featuredImage),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
    index("articles__status_idx").on(columns._status),
  ],
);

export const articles_locales = pgTable(
  "articles_locales",
  {
    title: varchar("title"),
    slug: varchar("slug"),
    excerpt: varchar("excerpt"),
    content: jsonb("content"),
    ensanaCTA_headline: varchar("ensana_c_t_a_headline"),
    ensanaCTA_text: varchar("ensana_c_t_a_text"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug, columns._locale),
    index("articles_meta_meta_image_idx").on(
      columns.meta_image,
      columns._locale,
    ),
    uniqueIndex("articles_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _articles_v_version_tags = pgTable(
  "_articles_v_version_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    tag: varchar("tag"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_articles_v_version_tags_order_idx").on(columns._order),
    index("_articles_v_version_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_articles_v.id],
      name: "_articles_v_version_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _articles_v = pgTable(
  "_articles_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => articles.id, {
      onDelete: "set null",
    }),
    version_type: enum__articles_v_version_type("version_type"),
    version_parentPillar: integer("version_parent_pillar_id").references(
      () => pages.id,
      {
        onDelete: "set null",
      },
    ),
    version_category: integer("version_category_id").references(
      () => categories.id,
      {
        onDelete: "set null",
      },
    ),
    version_author: integer("version_author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    version_featuredImage: integer("version_featured_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_ensanaCTA_enabled: boolean("version_ensana_c_t_a_enabled").default(
      false,
    ),
    version_ensanaCTA_url: varchar("version_ensana_c_t_a_url"),
    version_ensanaCTA_position: enum__articles_v_version_ensana_c_t_a_position(
      "version_ensana_c_t_a_position",
    ).default("sidebar"),
    version_status:
      enum__articles_v_version_status("version_status").default("draft"),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__articles_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__articles_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_articles_v_parent_idx").on(columns.parent),
    index("_articles_v_version_version_parent_pillar_idx").on(
      columns.version_parentPillar,
    ),
    index("_articles_v_version_version_category_idx").on(
      columns.version_category,
    ),
    index("_articles_v_version_version_author_idx").on(columns.version_author),
    index("_articles_v_version_version_featured_image_idx").on(
      columns.version_featuredImage,
    ),
    index("_articles_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_articles_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_articles_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_articles_v_created_at_idx").on(columns.createdAt),
    index("_articles_v_updated_at_idx").on(columns.updatedAt),
    index("_articles_v_snapshot_idx").on(columns.snapshot),
    index("_articles_v_published_locale_idx").on(columns.publishedLocale),
    index("_articles_v_latest_idx").on(columns.latest),
  ],
);

export const _articles_v_locales = pgTable(
  "_articles_v_locales",
  {
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_excerpt: varchar("version_excerpt"),
    version_content: jsonb("version_content"),
    version_ensanaCTA_headline: varchar("version_ensana_c_t_a_headline"),
    version_ensanaCTA_text: varchar("version_ensana_c_t_a_text"),
    version_meta_title: varchar("version_meta_title"),
    version_meta_description: varchar("version_meta_description"),
    version_meta_image: integer("version_meta_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("_articles_v_version_version_slug_idx").on(
      columns.version_slug,
      columns._locale,
    ),
    index("_articles_v_version_meta_version_meta_image_idx").on(
      columns.version_meta_image,
      columns._locale,
    ),
    uniqueIndex("_articles_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_articles_v.id],
      name: "_articles_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const people_stories = pgTable(
  "people_stories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    visitNumber: varchar("visit_number"),
    headline: varchar("headline"),
    pullQuote: varchar("pull_quote"),
    story: jsonb("story"),
    originalLanguage:
      enum_people_stories_original_language("original_language"),
    archetype: enum_people_stories_archetype("archetype"),
    portrait: integer("portrait_id").references(() => media.id, {
      onDelete: "set null",
    }),
    ensanaMention_mentioned: boolean("ensana_mention_mentioned").default(false),
    ensanaMention_context: varchar("ensana_mention_context"),
    consent_signed: boolean("consent_signed").default(false),
    consent_document: integer("consent_document_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    socialMedia_instagramPosted: boolean(
      "social_media_instagram_posted",
    ).default(false),
    socialMedia_instagramUrl: varchar("social_media_instagram_url"),
    socialMedia_facebookPosted: boolean("social_media_facebook_posted").default(
      false,
    ),
    socialMedia_facebookUrl: varchar("social_media_facebook_url"),
    featuredInNewsletter: boolean("featured_in_newsletter").default(false),
    status: enum_people_stories_status("status").default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_people_stories_status("_status").default("draft"),
  },
  (columns) => [
    index("people_stories_portrait_idx").on(columns.portrait),
    index("people_stories_consent_consent_document_idx").on(
      columns.consent_document,
    ),
    index("people_stories_updated_at_idx").on(columns.updatedAt),
    index("people_stories_created_at_idx").on(columns.createdAt),
    index("people_stories__status_idx").on(columns._status),
  ],
);

export const people_stories_locales = pgTable(
  "people_stories_locales",
  {
    country: varchar("country"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("people_stories_meta_meta_image_idx").on(
      columns.meta_image,
      columns._locale,
    ),
    uniqueIndex("people_stories_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [people_stories.id],
      name: "people_stories_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _people_stories_v = pgTable(
  "_people_stories_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => people_stories.id, {
      onDelete: "set null",
    }),
    version_name: varchar("version_name"),
    version_visitNumber: varchar("version_visit_number"),
    version_headline: varchar("version_headline"),
    version_pullQuote: varchar("version_pull_quote"),
    version_story: jsonb("version_story"),
    version_originalLanguage: enum__people_stories_v_version_original_language(
      "version_original_language",
    ),
    version_archetype:
      enum__people_stories_v_version_archetype("version_archetype"),
    version_portrait: integer("version_portrait_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_ensanaMention_mentioned: boolean(
      "version_ensana_mention_mentioned",
    ).default(false),
    version_ensanaMention_context: varchar("version_ensana_mention_context"),
    version_consent_signed: boolean("version_consent_signed").default(false),
    version_consent_document: integer("version_consent_document_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_socialMedia_instagramPosted: boolean(
      "version_social_media_instagram_posted",
    ).default(false),
    version_socialMedia_instagramUrl: varchar(
      "version_social_media_instagram_url",
    ),
    version_socialMedia_facebookPosted: boolean(
      "version_social_media_facebook_posted",
    ).default(false),
    version_socialMedia_facebookUrl: varchar(
      "version_social_media_facebook_url",
    ),
    version_featuredInNewsletter: boolean(
      "version_featured_in_newsletter",
    ).default(false),
    version_status:
      enum__people_stories_v_version_status("version_status").default("draft"),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__people_stories_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale:
      enum__people_stories_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_people_stories_v_parent_idx").on(columns.parent),
    index("_people_stories_v_version_version_portrait_idx").on(
      columns.version_portrait,
    ),
    index("_people_stories_v_version_consent_version_consent_docume_idx").on(
      columns.version_consent_document,
    ),
    index("_people_stories_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_people_stories_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_people_stories_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_people_stories_v_created_at_idx").on(columns.createdAt),
    index("_people_stories_v_updated_at_idx").on(columns.updatedAt),
    index("_people_stories_v_snapshot_idx").on(columns.snapshot),
    index("_people_stories_v_published_locale_idx").on(columns.publishedLocale),
    index("_people_stories_v_latest_idx").on(columns.latest),
  ],
);

export const _people_stories_v_locales = pgTable(
  "_people_stories_v_locales",
  {
    version_country: varchar("version_country"),
    version_meta_title: varchar("version_meta_title"),
    version_meta_description: varchar("version_meta_description"),
    version_meta_image: integer("version_meta_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("_people_stories_v_version_meta_version_meta_image_idx").on(
      columns.version_meta_image,
      columns._locale,
    ),
    uniqueIndex("_people_stories_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_people_stories_v.id],
      name: "_people_stories_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    credit: varchar("credit"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
    sizes_og_url: varchar("sizes_og_url"),
    sizes_og_width: numeric("sizes_og_width", { mode: "number" }),
    sizes_og_height: numeric("sizes_og_height", { mode: "number" }),
    sizes_og_mimeType: varchar("sizes_og_mime_type"),
    sizes_og_filesize: numeric("sizes_og_filesize", { mode: "number" }),
    sizes_og_filename: varchar("sizes_og_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
    index("media_sizes_og_sizes_og_filename_idx").on(columns.sizes_og_filename),
  ],
);

export const media_locales = pgTable(
  "media_locales",
  {
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("media_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [media.id],
      name: "media_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const authors = pgTable(
  "authors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    photo: integer("photo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    isEnsanaExpert: boolean("is_ensana_expert").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("authors_photo_idx").on(columns.photo),
    index("authors_updated_at_idx").on(columns.updatedAt),
    index("authors_created_at_idx").on(columns.createdAt),
  ],
);

export const authors_locales = pgTable(
  "authors_locales",
  {
    title: varchar("title"),
    bio: varchar("bio"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("authors_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [authors.id],
      name: "authors_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const categories_locales = pgTable(
  "categories_locales",
  {
    name: varchar("name").notNull(),
    description: varchar("description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("categories_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [categories.id],
      name: "categories_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events = pgTable(
  "events",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    category: enum_events_category("category"),
    isEnsanaEvent: boolean("is_ensana_event").default(false),
    ensanaLink: varchar("ensana_link"),
    status: enum_events_status("status").default("upcoming"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("events_slug_idx").on(columns.slug),
    index("events_image_idx").on(columns.image),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
  ],
);

export const events_locales = pgTable(
  "events_locales",
  {
    title: varchar("title").notNull(),
    description: jsonb("description"),
    location: varchar("location"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("events_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    pagesID: integer("pages_id"),
    articlesID: integer("articles_id"),
    "people-storiesID": integer("people_stories_id"),
    mediaID: integer("media_id"),
    authorsID: integer("authors_id"),
    categoriesID: integer("categories_id"),
    eventsID: integer("events_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_people_stories_id_idx").on(
      columns["people-storiesID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_authors_id_idx").on(columns.authorsID),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["people-storiesID"]],
      foreignColumns: [people_stories.id],
      name: "payload_locked_documents_rels_people_stories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "payload_locked_documents_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const navigation_main_menu_children = pgTable(
  "navigation_main_menu_children",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("navigation_main_menu_children_order_idx").on(columns._order),
    index("navigation_main_menu_children_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [navigation_main_menu.id],
      name: "navigation_main_menu_children_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const navigation_main_menu_children_locales = pgTable(
  "navigation_main_menu_children_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "navigation_main_menu_children_locales_locale_parent_id_uniqu",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [navigation_main_menu_children.id],
      name: "navigation_main_menu_children_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const navigation_main_menu = pgTable(
  "navigation_main_menu",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("navigation_main_menu_order_idx").on(columns._order),
    index("navigation_main_menu_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [navigation.id],
      name: "navigation_main_menu_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const navigation_main_menu_locales = pgTable(
  "navigation_main_menu_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("navigation_main_menu_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [navigation_main_menu.id],
      name: "navigation_main_menu_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const navigation = pgTable("navigation", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const footer_quick_links = pgTable(
  "footer_quick_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("footer_quick_links_order_idx").on(columns._order),
    index("footer_quick_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_quick_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_quick_links_locales = pgTable(
  "footer_quick_links_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("footer_quick_links_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer_quick_links.id],
      name: "footer_quick_links_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer = pgTable("footer", {
  id: serial("id").primaryKey(),
  socialLinks_instagram: varchar("social_links_instagram"),
  socialLinks_facebook: varchar("social_links_facebook"),
  socialLinks_youtube: varchar("social_links_youtube"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const footer_locales = pgTable(
  "footer_locales",
  {
    aboutText: varchar("about_text"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("footer_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    siteName: varchar("site_name").default("Marienbad.com"),
    defaultOgImage: integer("default_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    ga4MeasurementId: varchar("ga4_measurement_id"),
    gscVerification: varchar("gsc_verification"),
    mailerLiteApiKey: varchar("mailer_lite_api_key"),
    ensanaDefaults_baseUrl: varchar("ensana_defaults_base_url").default(
      "https://www.ensanahotels.com",
    ),
    ensanaDefaults_utmSource: varchar("ensana_defaults_utm_source").default(
      "marienbad.com",
    ),
    ensanaDefaults_utmMedium: varchar("ensana_defaults_utm_medium").default(
      "referral",
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("site_settings_default_og_image_idx").on(columns.defaultOgImage),
  ],
);

export const site_settings_locales = pgTable(
  "site_settings_locales",
  {
    tagline: varchar("tagline"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("site_settings_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_pages_table_of_contents_locales = relations(
  pages_table_of_contents_locales,
  ({ one }) => ({
    _parentID: one(pages_table_of_contents, {
      fields: [pages_table_of_contents_locales._parentID],
      references: [pages_table_of_contents.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_table_of_contents = relations(
  pages_table_of_contents,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_table_of_contents._parentID],
      references: [pages.id],
      relationName: "tableOfContents",
    }),
    _locales: many(pages_table_of_contents_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_faq_locales = relations(
  pages_faq_locales,
  ({ one }) => ({
    _parentID: one(pages_faq, {
      fields: [pages_faq_locales._parentID],
      references: [pages_faq.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_faq = relations(pages_faq, ({ one, many }) => ({
  _parentID: one(pages, {
    fields: [pages_faq._parentID],
    references: [pages.id],
    relationName: "faq",
  }),
  _locales: many(pages_faq_locales, {
    relationName: "_locales",
  }),
}));
export const relations_pages_target_keywords = relations(
  pages_target_keywords,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_target_keywords._parentID],
      references: [pages.id],
      relationName: "targetKeywords",
    }),
  }),
);
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: "_locales",
  }),
  meta_image: one(media, {
    fields: [pages_locales.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
}));
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: "_rels",
  }),
  articlesID: one(articles, {
    fields: [pages_rels.articlesID],
    references: [articles.id],
    relationName: "articles",
  }),
}));
export const relations_pages = relations(pages, ({ one, many }) => ({
  hero_backgroundImage: one(media, {
    fields: [pages.hero_backgroundImage],
    references: [media.id],
    relationName: "hero_backgroundImage",
  }),
  tableOfContents: many(pages_table_of_contents, {
    relationName: "tableOfContents",
  }),
  faq: many(pages_faq, {
    relationName: "faq",
  }),
  targetKeywords: many(pages_target_keywords, {
    relationName: "targetKeywords",
  }),
  _locales: many(pages_locales, {
    relationName: "_locales",
  }),
  _rels: many(pages_rels, {
    relationName: "_rels",
  }),
}));
export const relations__pages_v_version_table_of_contents_locales = relations(
  _pages_v_version_table_of_contents_locales,
  ({ one }) => ({
    _parentID: one(_pages_v_version_table_of_contents, {
      fields: [_pages_v_version_table_of_contents_locales._parentID],
      references: [_pages_v_version_table_of_contents.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__pages_v_version_table_of_contents = relations(
  _pages_v_version_table_of_contents,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_table_of_contents._parentID],
      references: [_pages_v.id],
      relationName: "version_tableOfContents",
    }),
    _locales: many(_pages_v_version_table_of_contents_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations__pages_v_version_faq_locales = relations(
  _pages_v_version_faq_locales,
  ({ one }) => ({
    _parentID: one(_pages_v_version_faq, {
      fields: [_pages_v_version_faq_locales._parentID],
      references: [_pages_v_version_faq.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__pages_v_version_faq = relations(
  _pages_v_version_faq,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_faq._parentID],
      references: [_pages_v.id],
      relationName: "version_faq",
    }),
    _locales: many(_pages_v_version_faq_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations__pages_v_version_target_keywords = relations(
  _pages_v_version_target_keywords,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_target_keywords._parentID],
      references: [_pages_v.id],
      relationName: "version_targetKeywords",
    }),
  }),
);
export const relations__pages_v_locales = relations(
  _pages_v_locales,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_locales._parentID],
      references: [_pages_v.id],
      relationName: "_locales",
    }),
    version_meta_image: one(media, {
      fields: [_pages_v_locales.version_meta_image],
      references: [media.id],
      relationName: "version_meta_image",
    }),
  }),
);
export const relations__pages_v_rels = relations(_pages_v_rels, ({ one }) => ({
  parent: one(_pages_v, {
    fields: [_pages_v_rels.parent],
    references: [_pages_v.id],
    relationName: "_rels",
  }),
  articlesID: one(articles, {
    fields: [_pages_v_rels.articlesID],
    references: [articles.id],
    relationName: "articles",
  }),
}));
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  version_hero_backgroundImage: one(media, {
    fields: [_pages_v.version_hero_backgroundImage],
    references: [media.id],
    relationName: "version_hero_backgroundImage",
  }),
  version_tableOfContents: many(_pages_v_version_table_of_contents, {
    relationName: "version_tableOfContents",
  }),
  version_faq: many(_pages_v_version_faq, {
    relationName: "version_faq",
  }),
  version_targetKeywords: many(_pages_v_version_target_keywords, {
    relationName: "version_targetKeywords",
  }),
  _locales: many(_pages_v_locales, {
    relationName: "_locales",
  }),
  _rels: many(_pages_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_articles_tags = relations(articles_tags, ({ one }) => ({
  _parentID: one(articles, {
    fields: [articles_tags._parentID],
    references: [articles.id],
    relationName: "tags",
  }),
}));
export const relations_articles_locales = relations(
  articles_locales,
  ({ one }) => ({
    _parentID: one(articles, {
      fields: [articles_locales._parentID],
      references: [articles.id],
      relationName: "_locales",
    }),
    meta_image: one(media, {
      fields: [articles_locales.meta_image],
      references: [media.id],
      relationName: "meta_image",
    }),
  }),
);
export const relations_articles = relations(articles, ({ one, many }) => ({
  parentPillar: one(pages, {
    fields: [articles.parentPillar],
    references: [pages.id],
    relationName: "parentPillar",
  }),
  category: one(categories, {
    fields: [articles.category],
    references: [categories.id],
    relationName: "category",
  }),
  author: one(authors, {
    fields: [articles.author],
    references: [authors.id],
    relationName: "author",
  }),
  featuredImage: one(media, {
    fields: [articles.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  tags: many(articles_tags, {
    relationName: "tags",
  }),
  _locales: many(articles_locales, {
    relationName: "_locales",
  }),
}));
export const relations__articles_v_version_tags = relations(
  _articles_v_version_tags,
  ({ one }) => ({
    _parentID: one(_articles_v, {
      fields: [_articles_v_version_tags._parentID],
      references: [_articles_v.id],
      relationName: "version_tags",
    }),
  }),
);
export const relations__articles_v_locales = relations(
  _articles_v_locales,
  ({ one }) => ({
    _parentID: one(_articles_v, {
      fields: [_articles_v_locales._parentID],
      references: [_articles_v.id],
      relationName: "_locales",
    }),
    version_meta_image: one(media, {
      fields: [_articles_v_locales.version_meta_image],
      references: [media.id],
      relationName: "version_meta_image",
    }),
  }),
);
export const relations__articles_v = relations(
  _articles_v,
  ({ one, many }) => ({
    parent: one(articles, {
      fields: [_articles_v.parent],
      references: [articles.id],
      relationName: "parent",
    }),
    version_parentPillar: one(pages, {
      fields: [_articles_v.version_parentPillar],
      references: [pages.id],
      relationName: "version_parentPillar",
    }),
    version_category: one(categories, {
      fields: [_articles_v.version_category],
      references: [categories.id],
      relationName: "version_category",
    }),
    version_author: one(authors, {
      fields: [_articles_v.version_author],
      references: [authors.id],
      relationName: "version_author",
    }),
    version_featuredImage: one(media, {
      fields: [_articles_v.version_featuredImage],
      references: [media.id],
      relationName: "version_featuredImage",
    }),
    version_tags: many(_articles_v_version_tags, {
      relationName: "version_tags",
    }),
    _locales: many(_articles_v_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_people_stories_locales = relations(
  people_stories_locales,
  ({ one }) => ({
    _parentID: one(people_stories, {
      fields: [people_stories_locales._parentID],
      references: [people_stories.id],
      relationName: "_locales",
    }),
    meta_image: one(media, {
      fields: [people_stories_locales.meta_image],
      references: [media.id],
      relationName: "meta_image",
    }),
  }),
);
export const relations_people_stories = relations(
  people_stories,
  ({ one, many }) => ({
    portrait: one(media, {
      fields: [people_stories.portrait],
      references: [media.id],
      relationName: "portrait",
    }),
    consent_document: one(media, {
      fields: [people_stories.consent_document],
      references: [media.id],
      relationName: "consent_document",
    }),
    _locales: many(people_stories_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations__people_stories_v_locales = relations(
  _people_stories_v_locales,
  ({ one }) => ({
    _parentID: one(_people_stories_v, {
      fields: [_people_stories_v_locales._parentID],
      references: [_people_stories_v.id],
      relationName: "_locales",
    }),
    version_meta_image: one(media, {
      fields: [_people_stories_v_locales.version_meta_image],
      references: [media.id],
      relationName: "version_meta_image",
    }),
  }),
);
export const relations__people_stories_v = relations(
  _people_stories_v,
  ({ one, many }) => ({
    parent: one(people_stories, {
      fields: [_people_stories_v.parent],
      references: [people_stories.id],
      relationName: "parent",
    }),
    version_portrait: one(media, {
      fields: [_people_stories_v.version_portrait],
      references: [media.id],
      relationName: "version_portrait",
    }),
    version_consent_document: one(media, {
      fields: [_people_stories_v.version_consent_document],
      references: [media.id],
      relationName: "version_consent_document",
    }),
    _locales: many(_people_stories_v_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_media_locales = relations(media_locales, ({ one }) => ({
  _parentID: one(media, {
    fields: [media_locales._parentID],
    references: [media.id],
    relationName: "_locales",
  }),
}));
export const relations_media = relations(media, ({ many }) => ({
  _locales: many(media_locales, {
    relationName: "_locales",
  }),
}));
export const relations_authors_locales = relations(
  authors_locales,
  ({ one }) => ({
    _parentID: one(authors, {
      fields: [authors_locales._parentID],
      references: [authors.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_authors = relations(authors, ({ one, many }) => ({
  photo: one(media, {
    fields: [authors.photo],
    references: [media.id],
    relationName: "photo",
  }),
  _locales: many(authors_locales, {
    relationName: "_locales",
  }),
}));
export const relations_categories_locales = relations(
  categories_locales,
  ({ one }) => ({
    _parentID: one(categories, {
      fields: [categories_locales._parentID],
      references: [categories.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_categories = relations(categories, ({ many }) => ({
  _locales: many(categories_locales, {
    relationName: "_locales",
  }),
}));
export const relations_events_locales = relations(
  events_locales,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_locales._parentID],
      references: [events.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_events = relations(events, ({ one, many }) => ({
  image: one(media, {
    fields: [events.image],
    references: [media.id],
    relationName: "image",
  }),
  _locales: many(events_locales, {
    relationName: "_locales",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    "people-storiesID": one(people_stories, {
      fields: [payload_locked_documents_rels["people-storiesID"]],
      references: [people_stories.id],
      relationName: "people-stories",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: "authors",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_navigation_main_menu_children_locales = relations(
  navigation_main_menu_children_locales,
  ({ one }) => ({
    _parentID: one(navigation_main_menu_children, {
      fields: [navigation_main_menu_children_locales._parentID],
      references: [navigation_main_menu_children.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_navigation_main_menu_children = relations(
  navigation_main_menu_children,
  ({ one, many }) => ({
    _parentID: one(navigation_main_menu, {
      fields: [navigation_main_menu_children._parentID],
      references: [navigation_main_menu.id],
      relationName: "children",
    }),
    _locales: many(navigation_main_menu_children_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_navigation_main_menu_locales = relations(
  navigation_main_menu_locales,
  ({ one }) => ({
    _parentID: one(navigation_main_menu, {
      fields: [navigation_main_menu_locales._parentID],
      references: [navigation_main_menu.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_navigation_main_menu = relations(
  navigation_main_menu,
  ({ one, many }) => ({
    _parentID: one(navigation, {
      fields: [navigation_main_menu._parentID],
      references: [navigation.id],
      relationName: "mainMenu",
    }),
    _locales: many(navigation_main_menu_locales, {
      relationName: "_locales",
    }),
    children: many(navigation_main_menu_children, {
      relationName: "children",
    }),
  }),
);
export const relations_navigation = relations(navigation, ({ many }) => ({
  mainMenu: many(navigation_main_menu, {
    relationName: "mainMenu",
  }),
}));
export const relations_footer_quick_links_locales = relations(
  footer_quick_links_locales,
  ({ one }) => ({
    _parentID: one(footer_quick_links, {
      fields: [footer_quick_links_locales._parentID],
      references: [footer_quick_links.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_footer_quick_links = relations(
  footer_quick_links,
  ({ one, many }) => ({
    _parentID: one(footer, {
      fields: [footer_quick_links._parentID],
      references: [footer.id],
      relationName: "quickLinks",
    }),
    _locales: many(footer_quick_links_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_footer_locales = relations(
  footer_locales,
  ({ one }) => ({
    _parentID: one(footer, {
      fields: [footer_locales._parentID],
      references: [footer.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_footer = relations(footer, ({ many }) => ({
  quickLinks: many(footer_quick_links, {
    relationName: "quickLinks",
  }),
  _locales: many(footer_locales, {
    relationName: "_locales",
  }),
}));
export const relations_site_settings_locales = relations(
  site_settings_locales,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_locales._parentID],
      references: [site_settings.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings = relations(
  site_settings,
  ({ one, many }) => ({
    defaultOgImage: one(media, {
      fields: [site_settings.defaultOgImage],
      references: [media.id],
      relationName: "defaultOgImage",
    }),
    _locales: many(site_settings_locales, {
      relationName: "_locales",
    }),
  }),
);

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_users_role: typeof enum_users_role;
  enum_pages_type: typeof enum_pages_type;
  enum_pages_ensana_c_t_a_position: typeof enum_pages_ensana_c_t_a_position;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_type: typeof enum__pages_v_version_type;
  enum__pages_v_version_ensana_c_t_a_position: typeof enum__pages_v_version_ensana_c_t_a_position;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum__pages_v_published_locale: typeof enum__pages_v_published_locale;
  enum_articles_type: typeof enum_articles_type;
  enum_articles_ensana_c_t_a_position: typeof enum_articles_ensana_c_t_a_position;
  enum_articles_status: typeof enum_articles_status;
  enum__articles_v_version_type: typeof enum__articles_v_version_type;
  enum__articles_v_version_ensana_c_t_a_position: typeof enum__articles_v_version_ensana_c_t_a_position;
  enum__articles_v_version_status: typeof enum__articles_v_version_status;
  enum__articles_v_published_locale: typeof enum__articles_v_published_locale;
  enum_people_stories_original_language: typeof enum_people_stories_original_language;
  enum_people_stories_archetype: typeof enum_people_stories_archetype;
  enum_people_stories_status: typeof enum_people_stories_status;
  enum__people_stories_v_version_original_language: typeof enum__people_stories_v_version_original_language;
  enum__people_stories_v_version_archetype: typeof enum__people_stories_v_version_archetype;
  enum__people_stories_v_version_status: typeof enum__people_stories_v_version_status;
  enum__people_stories_v_published_locale: typeof enum__people_stories_v_published_locale;
  enum_events_category: typeof enum_events_category;
  enum_events_status: typeof enum_events_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  pages_table_of_contents: typeof pages_table_of_contents;
  pages_table_of_contents_locales: typeof pages_table_of_contents_locales;
  pages_faq: typeof pages_faq;
  pages_faq_locales: typeof pages_faq_locales;
  pages_target_keywords: typeof pages_target_keywords;
  pages: typeof pages;
  pages_locales: typeof pages_locales;
  pages_rels: typeof pages_rels;
  _pages_v_version_table_of_contents: typeof _pages_v_version_table_of_contents;
  _pages_v_version_table_of_contents_locales: typeof _pages_v_version_table_of_contents_locales;
  _pages_v_version_faq: typeof _pages_v_version_faq;
  _pages_v_version_faq_locales: typeof _pages_v_version_faq_locales;
  _pages_v_version_target_keywords: typeof _pages_v_version_target_keywords;
  _pages_v: typeof _pages_v;
  _pages_v_locales: typeof _pages_v_locales;
  _pages_v_rels: typeof _pages_v_rels;
  articles_tags: typeof articles_tags;
  articles: typeof articles;
  articles_locales: typeof articles_locales;
  _articles_v_version_tags: typeof _articles_v_version_tags;
  _articles_v: typeof _articles_v;
  _articles_v_locales: typeof _articles_v_locales;
  people_stories: typeof people_stories;
  people_stories_locales: typeof people_stories_locales;
  _people_stories_v: typeof _people_stories_v;
  _people_stories_v_locales: typeof _people_stories_v_locales;
  media: typeof media;
  media_locales: typeof media_locales;
  authors: typeof authors;
  authors_locales: typeof authors_locales;
  categories: typeof categories;
  categories_locales: typeof categories_locales;
  events: typeof events;
  events_locales: typeof events_locales;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  navigation_main_menu_children: typeof navigation_main_menu_children;
  navigation_main_menu_children_locales: typeof navigation_main_menu_children_locales;
  navigation_main_menu: typeof navigation_main_menu;
  navigation_main_menu_locales: typeof navigation_main_menu_locales;
  navigation: typeof navigation;
  footer_quick_links: typeof footer_quick_links;
  footer_quick_links_locales: typeof footer_quick_links_locales;
  footer: typeof footer;
  footer_locales: typeof footer_locales;
  site_settings: typeof site_settings;
  site_settings_locales: typeof site_settings_locales;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_pages_table_of_contents_locales: typeof relations_pages_table_of_contents_locales;
  relations_pages_table_of_contents: typeof relations_pages_table_of_contents;
  relations_pages_faq_locales: typeof relations_pages_faq_locales;
  relations_pages_faq: typeof relations_pages_faq;
  relations_pages_target_keywords: typeof relations_pages_target_keywords;
  relations_pages_locales: typeof relations_pages_locales;
  relations_pages_rels: typeof relations_pages_rels;
  relations_pages: typeof relations_pages;
  relations__pages_v_version_table_of_contents_locales: typeof relations__pages_v_version_table_of_contents_locales;
  relations__pages_v_version_table_of_contents: typeof relations__pages_v_version_table_of_contents;
  relations__pages_v_version_faq_locales: typeof relations__pages_v_version_faq_locales;
  relations__pages_v_version_faq: typeof relations__pages_v_version_faq;
  relations__pages_v_version_target_keywords: typeof relations__pages_v_version_target_keywords;
  relations__pages_v_locales: typeof relations__pages_v_locales;
  relations__pages_v_rels: typeof relations__pages_v_rels;
  relations__pages_v: typeof relations__pages_v;
  relations_articles_tags: typeof relations_articles_tags;
  relations_articles_locales: typeof relations_articles_locales;
  relations_articles: typeof relations_articles;
  relations__articles_v_version_tags: typeof relations__articles_v_version_tags;
  relations__articles_v_locales: typeof relations__articles_v_locales;
  relations__articles_v: typeof relations__articles_v;
  relations_people_stories_locales: typeof relations_people_stories_locales;
  relations_people_stories: typeof relations_people_stories;
  relations__people_stories_v_locales: typeof relations__people_stories_v_locales;
  relations__people_stories_v: typeof relations__people_stories_v;
  relations_media_locales: typeof relations_media_locales;
  relations_media: typeof relations_media;
  relations_authors_locales: typeof relations_authors_locales;
  relations_authors: typeof relations_authors;
  relations_categories_locales: typeof relations_categories_locales;
  relations_categories: typeof relations_categories;
  relations_events_locales: typeof relations_events_locales;
  relations_events: typeof relations_events;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_navigation_main_menu_children_locales: typeof relations_navigation_main_menu_children_locales;
  relations_navigation_main_menu_children: typeof relations_navigation_main_menu_children;
  relations_navigation_main_menu_locales: typeof relations_navigation_main_menu_locales;
  relations_navigation_main_menu: typeof relations_navigation_main_menu;
  relations_navigation: typeof relations_navigation;
  relations_footer_quick_links_locales: typeof relations_footer_quick_links_locales;
  relations_footer_quick_links: typeof relations_footer_quick_links;
  relations_footer_locales: typeof relations_footer_locales;
  relations_footer: typeof relations_footer;
  relations_site_settings_locales: typeof relations_site_settings_locales;
  relations_site_settings: typeof relations_site_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
